/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NameSystem } from "./NameSystem";
export * as factories from "./factories";
export { NameSystem__factory } from "./factories/NameSystem__factory";
