/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BadgeToken__factory } from "./BadgeToken__factory";
export { NameSystem__factory } from "./NameSystem__factory";
